### ISSUE TITLE
Question on Initial Values

### ISSUE THREAD

**Issue by scath999** [mitmedialab/TI_EVM_logger#1]
Thanks so much for writing this and publishing.

Your project totally works, but as a new hardware developer I'm a little confused and hoping for some guidance: Page 43 of the [datasheet](https://www.ti.com/lit/ds/symlink/fdc2214.pdf) gives a recommended set of initial values that differ in some places from your defaults. 

I'm curious if the datasheet I'm referencing is different than the one you used, or if your field testing led you to start with different default values. 

Thank you again for contributing this - it's helping me learn a lot.

Best wishes,

S.

**Comment by honnet** [comment]
Thanks for the warm comments!

Is there a specific (set of) parameter (s) that you're curious about?

**Comment by scath999** [comment]
Thanks for writing back, and so quickly :)

There are four that differ from the datasheet; again, don't mean to second guess you - I'm just learning. 

EVM_RCOUNT_ (CH0 to 3): Your default: 0xFFFF. TI's recommended default: 0x8329.
EVM_SETTLECOUNT_ (CH0 to 3): Your default: 0x0001. TI's recommended default: 0x000A.
EVM_CLOCK_DIVIDERS_ (CH0 to 3): Your default: 0x1001. TI's recommended default: 0x2002.
EVM_CLOCK_DIVIDERS_ (CH0 to 3): Your default: 0xF800. TI's recommended default: 0x7C00

I may be reading the datasheet incorrectly, or not completely understanding it. If so, please forgive my ignorance ;) 

Thanks again for even writing back. I'm sure you've moved on to other things, so I appreciate the time and patience.

Best wishes and thanks!

**Comment by honnet** [comment]
Ah! These parameters came from the repo I linked at the bottom of the readme, more specifically, this file:

https://github.com/2n3906/ldc1614evm_logger/blob/master/ldc1614evm_logger.py

**Comment by scath999** [comment]
I see!

It seems like those values came from another board, and just worked?

Is there any danger is using the defaults? (Not to be pedantic, I'm just really new to firmware dev).

**Comment by scath999** [comment]
Thanks again :)

**Comment by honnet** [comment]
It's very good to ask the question for sure.

Sometimes it's ok for quick tests, and keep them if everything works :)

**Comment by honnet** [comment]
PS: can you close the issue? (if you have your answers)

**Comment by scath999** [comment]
lol absolutely :) Thanks again!

**Comment by honnet** [comment]
Thanks!
